name: Deploy backend to Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        working-directory: backend

      - name: Zip backend code
        run: zip -r ../revox-backend.zip . -x "*.env"
        working-directory: backend

      - name: Deploy Lambda
        uses: appleboy/lambda-action@v0.1.5
        with:
          function_name: revox-backend
          region: eu-west-3
          zip_file: revox-backend.zip
          access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: List files for debug
        run: ls -la